apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: sample-k8s-app
  labels:
    app: sample-k8s-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-k8s-api
  template:
    metadata:
      labels:
        app: sample-k8s-api
    spec:
      containers:
      - name: api
        image: thcerutti/sample-k8s-app-api:latest
        # Imagem pública construída via CI. Use tag de commit para releases imutáveis (ex: :<GIT_SHA>).
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
