apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-files
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>My sample k8s app</title>
      </head>
      <body>
        <h1>Welcome to my sample k8s app!</h1>
        <p>This is a simple frontend application.</p>
        <button id="myButton">Click me!</button>
        <script type="module">
          import { fetchData } from "./requests.js";

          document.getElementById("myButton").addEventListener("click", () => {
            // Mudamos para usar o caminho /api/ que será redirecionado pelo nginx
            fetchData("/api/").then(data => {
              alert(`Mensagem da API: ${data.message}`);
            });
          });
        </script>
      </body>
    </html>
  requests.js: |
    function fetchData(endpoint) {
      return fetch(endpoint)
        .then(response => response.json())
        .catch(error => console.error('Error fetching data:', error));
    }

    export { fetchData };
