apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: sample-k8s-api
spec:
  selector:
    app: sample-k8s-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
